Update repo, commit 47960bdb9eece2590ef4f36cae74a3896a262946

diff --git a/util-scripts/oasync b/util-scripts/oasync
--- a/util-scripts/oasync
+++ b/util-scripts/oasync
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Define the directories to include in the stash
-items_to_include="
+dirs_to_exclude="
 config/
 systemd/
 "
@@ -16,7 +16,7 @@ current_date=$(date +"%Y-%m-%d %H:%M:%S")
 current_commit=$(git rev-parse --short HEAD)
 
 # Create a temporary stash
-git stash push -u -m "Temp stash for comparison" -- $items_to_include > /dev/null 2>&1 || { echo "Error: Could not create temporary stash"; exit 1; }
+git stash push -u -m "Temp stash for comparison" -- $dirs_to_exclude > /dev/null 2>&1 || { echo "Error: Could not create temporary stash"; exit 1; }
 
 # Check if the temporary stash is the same as the last stash
 if git stash list | grep -q 'stash@{1}' && git diff stash@{0} stash@{1} --quiet; then
@@ -27,7 +27,7 @@ else
     # Apply the temporary stash
     git stash apply stash@{0} > /dev/null 2>&1 || { echo "Error: Could not apply temporary stash"; exit 1; }
     # Create a new stash with the desired message
-    git stash push -u -m "Date: $current_date, Commit: $current_commit" -- $items_to_include > /dev/null 2>&1 || { echo "Error: Could not create new stash"; exit 1; }
+    git stash push -u -m "Date: $current_date, Commit: $current_commit" -- $dirs_to_exclude > /dev/null 2>&1 || { echo "Error: Could not create new stash"; exit 1; }
     # Drop the temporary stash
     git stash drop stash@{1} > /dev/null 2>&1 || { echo "Error: Could not drop temporary stash"; exit 1; }
 fi
